### ISSUE TITLE
joining giveaways

### ISSUE THREAD

**Issue by MajorLOL** [kernelcoffee/SteamSelfGifter#2]
Seems like only joins games on wishlist, how can i change this?

**Comment by kernelcoffee** [comment]
It does check against the regular list as well, however there are restrictions which you can change in the settings.
```
upper_threshold=350 # the required amount of credit before it looks into the main list
lower_threshold=200 # the minimum amount of credit left for the wishlist

# This section is for the requirement on the games to automatically apply for outside of the wishlist
[game]
min_price=10 # minimum price in the currency listed on steam
min_score=7 # overall score on the game, 7 would be mostly positive
min_reviews=500 # mininum amount of people leaving a review
```

The idea spend the credits of giveaways while not applying for trash games and leaving enough if you have wishlisted games arriving (which are the priority).

**Comment by MajorLOL** [comment]
currently i have 400 points and it is not joining anything.
All curreny wishlist games are entered.

The given settings are used. also changing the PHPSESSID with a newer one did not fix it.

Thanks for the work tho, love it :)

Lowered to:
[misc]
logging="INFO"
upper_threshold=200
lower_threshold=100

[game]
min_price=10
min_score=4
min_reviews=500

Same results

**Comment by kernelcoffee** [comment]
There are still a lot of rough edges any feedback is welcome :)

Are you able to see the logs ? (don't mind the parsing errors, I haven't figured out all of them)
if you see `Found <number> games to review` then it will look into the main list.

Also there is a fair amount of random waiting time in between entering giveaways in order to avoid spamming the site

**Comment by MajorLOL** [comment]
Hi there again, i let it run overnight.

It seems to join random giveaway now,
The only errors i see are:

- 'SteamGame' object   has no attribute 'modified_at'
- Could not get steam   game data: Giveaway is a bundle, let's skip for   https://store.steampowered.com/api/appdetails?appids=225140&json=1

I would make a set time to auto join top prioriy if i were you, Currently we are logged in 24 hours a day.

**Comment by kernelcoffee** [comment]
> Hi there again, i let it run overnight.
> 
> It seems to join random giveaway now,

Glad to know that it works for you as well :)

There seems to be a delay after which it properly starts, as it is running it is building a cache in order to make it faster, I'll investigate that.

> The only errors i see are:
> 
>     * 'SteamGame' object   has no attribute 'modified_at'
Yes, this is expected, this is part of the parsing issue I haven't figured out just yet
> 
>     * Could not get steam  game data: Giveaway is a bundle, let's skip for   https://store.steampowered.com/api/appdetails?appids=225140&json=1
This is part the project, this is a bundle, so a collection of games and I haven't been able to properly handle it, so I skip it for now.
> 
> 
> I would make a set time to auto join top prioriy if i were you, Currently we are logged in 24 hours a day.

Yes, it's in my todo list, I'll get back to working on this project now that I know I'm not the only one using it ;) (as it reached a "good enough for my needs" state)
That being said, I've been running it for the past few months and had no issue so far, I'm not sure if they keep track, also I've built it to be "gentle" with fair amount of cache and wait time in between joining giveaways.

Thank you for your feedback ^^
